# Generated by Django 5.0.6 on 2024-06-10 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_groupe_dateenvoie_remove_groupe_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='backend.projet'),
        ),
        migrations.RemoveField(
            model_name='projet',
            name='groupe',
        ),
        migrations.DeleteModel(
            name='Groupe',
        ),
    ]
