# Generated by Django 5.0.6 on 2024-06-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_messages_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorate',
            name='supervisor',
        ),
    ]
