# Generated by Django 5.0.6 on 2024-06-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_publication_likes_followingpublication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='following',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='recommendations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='saving',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
